name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER:  ${{secrets.DOCKER_PASSWORD}}
                  echo "$DOCKER_USER" | sed 's/./& /g' 
      run:  |
        docker login -u "$DOCKER_USER" -p dckr_pat_l4_z1bfuZPsRutp1k2fTRZo_L5o
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mpierce80/unifi:6.5.55

    - name: Docker Push
      run: docker push mpierce80/unifi:6.5.55
