name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER:  ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD:  ${{secrets.DOCKER_PASSWORD}}
      run:  |
        docker login -u mpierce80 -p dckr_pat_l4_z1bfuZPsRutp1k2fTRZo_L5o
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mpierce80/unifi:$(date +%s)

    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/mpierce80/unifi
